# .circleci/config.yml  (CircleCI 2.1)
version: 2.1

executors:
  docker-dind:
    # machine executor gives you full Docker daemon + BuildKit
    machine:
      image: ubuntu-2204:current        # CircleCI’s stock Ubuntu image
    environment:
      DOCKER_BUILDKIT: 1                # enable BuildKit everywhere

jobs:
  build_and_push:
    executor: docker-dind
    steps:
      - checkout

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PAT" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Build & push
          command: |
            TAG="${CIRCLE_TAG:-latest}"
            docker build --progress=plain -t "docker.io/$DOCKERHUB_USER/comfyui-discord-bot-wan:${TAG}" .
            docker push "docker.io/$DOCKERHUB_USER/comfyui-discord-bot-wan:${TAG}"

workflows:
  version: 2
  build_on_tag:
    jobs:
      - build_and_push:
          context: docker-hub
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/   # run on tags like v5 or v1.2.3
            branches:
              ignore: /.*/